### ISSUE TITLE
Proposal: Migration to CodeMirror 6 editor

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#1002]
### Background
Code App uses Monaco Editor as its core text editor. It is feature-rich and compatible with VS Code features that our users are familiar with. However, its mobile unfriendliness makes the app incredibly difficult to use for users without access to a physical keyboard:
- #20 
- #169 
- #280 
- #584 
- #958 
- #997 

### Altenative
CodeMirror 6 is a performant and mobile-friendly editor alternative to Monaco. All native iOS text selection gestures are supported properly.

Left: Monaco with TextMate; Right: CM6
![image](https://github.com/thebaselab/codeapp/assets/38398443/a8671908-da71-4bbc-8699-ae6e378670d0)

### TODOs:
Identify the missing features and lay out a plan for development and integration:
- [ ] Styling and touch controls of mini-map (https://github.com/replit/codemirror-minimap)
- [ ] Line number styling
- [ ] Custom search widget
- [ ] State restoration
- [ ] Gutter area and diff algorithm for Git decorations
- [ ] Theme converter (Textmate -> CM6)
- [ ] Language definitions (Challenging, is it possible to convert or use text mate definitions directly?)
- [ ] Diff editor
- [ ] VIM (https://github.com/replit/codemirror-vim)
- [ ] URL detections
- [ ] APIs for interacting with the editor:
  - Callbacks on editor state update (e.g. content / cursor changed)
  - Storage for multiple editors
- Rethink the APIs used to interact with Native code / SwiftUI
 - etc

**Comment by rxx** [comment]
I will be waiting for that. Without touch support it's unacceptable to me using any vscode-related editors on my phone.

**Comment by AnthonyGress** [comment]
+1

**Comment by bummoblizard** [comment]
Closing since we implemented Runestone editor instead.
