### ISSUE TITLE
Proposal: Language Service Implementation (LSP)

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#1104]
## Background
Language Service Protocol is a protocol between code editor and a language server that provides code analysis features like autocompletion. Now with the mature local languages and app extension support in Code App, it is time to design and build the architecture necessary to implement LSP features.

### Server
We would run the language server implementation in an iOS app extension because:
- Language servers are prone to crashes, especially in a patched, non supported environment, we do not want the whole app to crash when they encountered errors
- Language runtime interferes with each other in a single process

This implies the language server must keep its memory usage low (~120MB). Careful configuration and crash recovery are necessary.

Websocket endpoints:
- `lsp/{language_identifier}`: Request to start language server
- `execution/`: Request to start code execution

Requests are then accepted / rejected subject to resources availability. If accepted, stream stdio over web socket.

### Client
Use [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) to connect monaco editor to LSP using WebSocket.

```js
async function connectMonacoToLanguageServer(languageIdentifier, serverURL) {}

async function disconnectLanguageServer(languageIdentifier?) {}

function languageServerConnectionDidDrop(languageIdentifier) {}

```

(To be added..)

## TODOs:
- [ ] Design the editor-server communication protocol
  - WebSocket or Posix socket?
  - When to start or stop a language server? 
  - What to do when user requests code execution when there can only be one runtime instance? (Java, Node.js)
  - What to do with multiple scene? A language server serves one editor at a time.
- [ ] Build the client using monaco-languageclient
- [ ] Build the server
  - A web socket server that redirects stdio/stdin in ios_system / main thread
  - Implementation of any crash recovery protocol 
  - Integration of the actual language servers

Some candidates of language server to integrate:
- https://github.com/pappasam/jedi-language-server (Python)
- https://github.com/georgewfraser/java-language-server (Java)
- https://github.com/typescript-language-server/typescript-language-server (TypeScript / JavaScript)

**Comment by bummoblizard** [comment]
Python / Java Intellisense is now available in our latest TestFlight build.

**Comment by valdo404** [comment]
Hi, I would like to share my thoughts on this task.

currently the ipad does not have a real good capability to support many languages and their tools.

I guess combining codeapp with cloud launched lsp servers for indexing, crawling, compiling, and debugging large software projects would be quite interesting.

as such I think the lsp server shouldn't be local but launched on the cloud.

I'm about to clone this project to test the idea of launching actions on a cloud based project (with a local mirror that is using file synchronisation)

best

**Comment by KagaJiankui** [comment]
Hope to see markdown and clangd language server integrated with the CodeApp, and a outline sidebar like that in VSCode.

By the way, cloud-based language server may suffer from lagging and disconnection problems under many edge scenarios, for example on mobile traveling and in less connected areas.
